name: Refresh

on:
  workflow_dispatch:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: |
        mkdir output/
        chmod 777 chromedriver
        python refresh.py
    - name: Pushes to Free-Proxies
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@devel
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: output/
        destination-github-username: 'saschazesiger'
        destination-repository-name: 'Free-Proxies'
        user-email: janis.zesiger@gmail.com
        commit-message: Refresh
        target-branch: main
