name: Auto Update

on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4 selenium
    - run: curl -s -L https://raw.githubusercontent.com/saschazesiger/Proxy-List/main/refresh.py -o refresh.py
    - run: python refresh.py
    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.GIT_EMAIL }}
        git config --local user.name ${{ secrets.GIT_NAME }}
        git commit -am "Updated Proxies"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true

