name: Updater

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python -m pip install --upgrade pip
      run: pip install requests selenium bs4
      run: curl -s -L https://raw.githubusercontent.com/saschazesiger/Proxy-List/main/refresh.py -o refresh.py
      run: curl -s -L https://raw.githubusercontent.com/saschazesiger/Proxy-List/main/chromedriver.exe -o chromedriver.exe
    - name: Run Update
    - run: python refresh.py
